# Generated by Django 4.2 on 2026-01-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['stage_name'],
            },
        ),
    ]
